### ISSUE TITLE
Glances Addon fails to start

### ISSUE THREAD

**Issue by danrspencer** [hassio-addons/addon-glances#15]
# Problem/Motivation

The addon doesn't start. 

## Expected behavior

It starts

## Actual behavior

It doesn't start, I get the following log output:

```
INFO: Starting Glances...
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.0', 'console_scripts', 'glances')()
  File "/usr/local/lib/python3.7/site-packages/glances/__init__.py", line 140, in main
    start(config=config, args=args)
  File "/usr/local/lib/python3.7/site-packages/glances/__init__.py", line 106, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/local/lib/python3.7/site-packages/glances/webserver.py", line 41, in __init__
    self.stats.update()
  File "/usr/local/lib/python3.7/site-packages/glances/stats.py", line 222, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.7/site-packages/glances/plugins/glances_processcount.py", line 71, in update
    glances_processes.update()
  File "/usr/local/lib/python3.7/site-packages/glances/processes.py", line 247, in update
    ad_value=None)
  File "/usr/local/lib/python3.7/site-packages/glances/processes.py", line 246, in <listcomp>
    self.processlist = [p.info for p in psutil.process_iter(attrs=standard_attrs,
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 1562, in process_iter
    yield add(pid)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 1539, in add
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
  File "/usr/local/lib/python3.7/site-packages/psutil/__init__.py", line 623, in as_dict
    ", ".join(map(repr, invalid_names))))
ValueError: invalid attr name 'io_counters'
```

It keeps attempting to start and showing this error in a loop until manually stopped.

## Steps to reproduce

The addon does this every time I restart it. I've uninstalled it and reinstalled to no effect.

**Comment by charlietomo** [comment]
This may or may not be related but I also have an issue with it not starting.
`PANIC: unprotected error in call to Lua API (bad light userdata pointer)`
I suspect my issue is the same issue impacting a number of add-ons, related to using the `aarch64` (the only option I'm aware of on an Odroid C1).

**Comment by frenck** [comment]
@charlietomo This is in no way related at all. Please create separate issues in case you are in doubt. Thanks.

**Comment by danrspencer** [comment]
I just realised that I completely failed to mention in my original issue that this is with Hassio running on an Asus Tinker Board.

**Comment by aruff72** [comment]
I too am getting the same error on an Asus tinkerboard. I just installed and uninstalled several times but it just loops at that point. Does this work with arm7 or this board?
Thanks
