### ISSUE TITLE
No export to influxDB after previous fix

### ISSUE THREAD

**Issue by MaelJego** [hassio-addons/addon-glances#302]
Problem/Motivation
See previous issue https://github.com/hassio-addons/addon-glances/issues/296#issue-1442409885
and previous fix https://github.com/hassio-addons/addon-glances/pull/299
No change same error

The export to influxDB no longer works.

Expected behavior

The export works without issues.
Actual behavior

No data are in the relevant influxDB DB.

module 'six' is not installed (I have checked in the container).

![2022-11-17 19_36_05-](https://user-images.githubusercontent.com/99092881/202532136-5fc7f126-caaf-4754-97cf-b978d88d5d66.png)

Add-on: Glances
A cross-platform system monitoring tool
Add-on version: 0.17.1
You are running the latest version of this add-on.
System: Home Assistant OS 9.3 (amd64 / generic-x86-64)
Home Assistant Core: 2022.11.3
Home Assistant Supervisor: 2022.10.2
Please, share the above information when looking for help
or support in, e.g., GitHub, forums or the Discord chat.

INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
File "/usr/bin/glances", line 8, in
sys.exit(main())
File "/usr/lib/python3.10/site-packages/glances/init.py", line 179, in main
start(config=core.get_config(), args=core.get_args())
File "/usr/lib/python3.10/site-packages/glances/init.py", line 108, in start
mode = GlancesMode(config=config, args=args)
File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in init
self.stats = GlancesStats(config=config, args=args)
File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in init
self.load_modules(self.args)
File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
self.load_exports(args=args)
File "/usr/lib/python3.10/site-packages/glances/stats.py", line 162, in load_exports
export_module = import(self._exports_all[export_name])
File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 18, in
from influxdb import InfluxDBClient
File "/usr/lib/python3.10/site-packages/influxdb/init.py", line 9, in
from .client import InfluxDBClient
File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 23, in
from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'

Steps to reproduce

Setup influxDB in Glances.

**Comment by Zarzook** [comment]
Same problem as @MaelJego  still 
-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.17.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 162, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 18, in <module>
    from influxdb import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/__init__.py", line 9, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'

**Comment by TheDK** [comment]
Same problem:

```
-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.17.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / odroid-n2)
 Home Assistant Core: 2022.11.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 162, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 18, in <module>
    from influxdb import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/__init__.py", line 9, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'
```

**Comment by TheDK** [comment]
@ferrix Would you mind taking a look? Thanks!

**Comment by pedrojreis** [comment]
I also have the same issue, just wanted to add that it seems that this problem started since 0.17.0 as I lost influx logs since the 10th of November.

**Comment by chichin79** [comment]
Dont know if it's relevant but same problem here, same error code as above: ModuleNotFoundError: No module named 'six'

**Comment by DarkShadow-1** [comment]
Same problem as all above with same error

**Comment by SantaFox** [comment]
Confirmed.

```
-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.17.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2022.12.1
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/standalone.py", line 45, in __init__
    self.stats = GlancesStats(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 162, in load_exports
    export_module = __import__(self._exports_all[export_name])
  File "/usr/lib/python3.10/site-packages/glances/exports/glances_influxdb.py", line 18, in <module>
    from influxdb import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/__init__.py", line 9, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/python3.10/site-packages/influxdb/client.py", line 23, in <module>
    from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'
```
