### ISSUE TITLE
InfluxDB 2 export no longer functions after upgrading to v0.19.0

### ISSUE THREAD

**Issue by doolbneerg** [hassio-addons/addon-glances#362]
# Problem/Motivation

Just upgraded to version 0.19.0 and InfluxDB2 export doesn't appear to be working.

## Expected behavior

InfluxDB2 export continue to work.

## Actual behavior

No data is being exported to InfluxDB2.

Here is my log:
```
-----------------------------------------------------------
 Add-on: Glances
 A cross-platform system monitoring tool
-----------------------------------------------------------
 Add-on version: 0.19.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (aarch64 / yellow)
 Home Assistant Core: 2023.5.3
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
INFO: Starting Glances...
Glances Web User Interface started on http://127.0.0.1:61209/
INFO: Starting NGinx...
Traceback (most recent call last):
  File "/usr/bin/glances", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/glances/__init__.py", line 180, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.11/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/glances/standalone.py", line 44, in __init__
    self.stats = GlancesStats(config=config, args=args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/glances/stats.py", line 39, in __init__
    self.load_modules(self.args)
  File "/usr/lib/python3.11/site-packages/glances/stats.py", line 90, in load_modules
    self.load_exports(args=args)
  File "/usr/lib/python3.11/site-packages/glances/stats.py", line 167, in load_exports
    self._exports[export_name] = export_module.Export(args=args, config=self.config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/glances/exports/glances_influxdb2.py", line 52, in __init__
    self.interval = int(self.interval)
                    ^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
````

## Steps to reproduce

Upgrade to v0.19.0 and attempt to use InfluxDB2.

**Comment by doolbneerg** [comment]
I am marking this as closed as v0.19.1 fixed the issue. It looks like it was an issue with glances itself.  https://github.com/nicolargo/glances/issues/2407
